### PR TITLE
feat: Added support for environments during registration

### PR DESCRIPTION
**Pull request by jirihnidek**
* It is possible to specify environments during connecting (RHSM registration) using CLI option --environment
* It is possible to specify multiple environmets
* Added beforeCoonectAction checking combinations of CLI options

### CODE REVIEW

**Comment by jirihnidek** [comment]
To test this functionality it is necessary to create some testing environments. If you use local candlepin server, then you create new environments using following commands:

```
curl --stderr /dev/null --insecure --user admin:admin --request POST \
  --data '{"id": "env-id-1", "name": "env-name-1", "description": "Testing environment num. 1"}' \
  --header 'accept: application/json' --header 'content-type: application/json' \
  https://localhost:8443/candlepin/owners/donaldduck/environments
```

```
curl --stderr /dev/null --insecure --user admin:admin --request POST \
  --data '{"id": "env-id-2", "name": "env-name-2", "description": "Testing environment num. 2"}' \
  --header 'accept: application/json' --header 'content-type: application/json' \
  https://localhost:8443/candlepin/owners/donaldduck/environments
```

Then you can test connecting system using `rhc` using following command:

```
./rhc connect --username admin --password admin --organization donaldduck \
  --environment env-id-1 --environment env-id-2
```

As you can see, you can use CLI option `--environment` multiple times, because system could become member of more environments.

There is no command that could be used for getting list of valid environments, because there is no D-Bus API for getting such list. User just has to know IDs of environments.

It is also reason why `rhc` does not ask for environment (like subscription-manager), when no environment is provided using CLI option, but organization contains some environments. In that case system will be just registered, but system will not belong to any environment.

**Comment by jirihnidek** [comment]
Build started 10:40 ...

**Review by Lorquas — APPROVED** [review]
The code looks good to me, concise and easy to follow.  Thanks for the environment steps.  I tested this against a rhel-9 machine and selinux denied rhc from accessing subscription-manager?

Outside of that the environments successfully connect, and the activation-key errors in the beforeConnectAction work as expected.  

LGTM after a rebase.

**Comment by rehana-raj** [comment]
We agreed to delay merging of this PR until we confirm the requirements with depend teams.

**Comment by jirihnidek** [comment]
Closing this PR due to this: https://issues.redhat.com/browse/RHEL-53436  We can reopen later, when needed.

**Pull request closed without merging**
