### PR TITLE
packit: tag cloud resources in Testing Farm

### PR DESCRIPTION
**Pull request by thrix**
This way we can track the cloud costs for the team and also provide more detailed team specific metrics.

### CODE REVIEW

**Comment by Lorquas** [comment]
Can one of the admins verify this patch?

**Comment by thrix** [comment]
Also let's wait for tests, so we can verify it is doing what it should be

**Comment by jirihnidek** [comment]
@thrix Thanks for PR. Can you please modify little bit commit message? The commit message should begin with one of the following category keyword: "build,ci,chore,docs,feat,fix,perf,refactor,revert,style,test"

**Comment by Lorquas** [comment]
Jenkins test this please.

**Comment by thrix** [comment]
hopefully ok now

**Review by jirihnidek — APPROVED** [review]
LGTM, thanks

**Pull request merged**
